services:
  db:
    image: docker.io/library/mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - project_scars-central_server_database:/var/lib/mysql
    env_file:
      - .env

  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    restart: always
    ports:
      - 32512:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db

volumes:
  project_scars-central_server_database:
