# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "uv" # See documentation for possible values
      directory: "/CentralServer" # Location of package manifests
      schedule:
          interval: "daily"
      open-pull-requests-limit: 10
      labels:
          - "tag > bot"
          - "kind > dependencies"
          - "scope > central server"
    - package-ecosystem: "npm" # See documentation for possible values
      directory: "/WebClient" # Location of package manifests
      schedule:
          interval: "daily"
      open-pull-requests-limit: 10
      groups:
          mantine:
              patterns:
                  - "@mantine/*"
      labels:
          - "tag > bot"
          - "kind > dependencies"
          - "scope > web client"
