x-depends_on: &default-depends_on
  - postgres
  - redis

services:
  postgres:
    image: docker.io/library/postgres:17
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: docker.io/valkey/valkey
    restart: unless-stopped
  web:
    image: docker.io/glitchtip/glitchtip
    depends_on: *default-depends_on
    ports:
      - "8085:8085"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  worker:
    image: docker.io/glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  migrate:
    image: docker.io/glitchtip/glitchtip
    depends_on: *default-depends_on
    command: ./bin/run-migrate.sh
    env_file:
      - .env

volumes:
  pg-data:
  uploads:
