coverage:
  range: 75...85
  round: nearest
  precision: 2

comment:
  layout: "header, diff, flags, files, footer"
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true

  individual_flags:
    - name: central-server
      paths:
        - "CentralServer/**"

    - name: web-client
      paths:
        - "WebClient/**"
