coverage:
  range: 75...85
  round: nearest
  precision: 2

comment:
  layout: "header, diff, flags, files, footer"
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: patch
        target: 90%

  individual_flags:
    - name: central-server
      paths:
        - CentralServer/

    - name: local-server
      paths:
        - LocalServer/

    - name: web-client
      paths:
        - WebClient/
