services:
    centralserver:
        build:
            context: ./CentralServer
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        volumes:
            - project_scars-centralserver:/app
            - ./CentralServer/config.prod.json:/app/config.json:ro
        restart: unless-stopped

    webclient:
        build:
            context: ./WebClient
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - centralserver

volumes:
    project_scars-centralserver:
        driver: local

networks:
    default:
        driver: bridge
        name: project_scars_network
