services:
    centralserver-garage:
        image: docker.io/dxflrs/garage:v2.0.0-rc1
        ports:
            - "3900:3900"
            - "3901:3901"
            - "3902:3902"
            - "3903:3903"
        volumes:
            - ./garage.toml:/etc/garage.toml
            - centralserver-garage_meta:/var/lib/garage/meta
            - centralserver-garage_data:/var/lib/garage/data
        restart: unless-stopped

volumes:
    centralserver-garage_data:
    centralserver-garage_meta:
