services:
  cloudflared:
    image: wisdomsky/cloudflared-web:latest
    restart: unless-stopped
    network_mode: host
    # compatibility with Docker Desktop,
    # since it uses WSL2.
    ports:
      - "14333:14333"