services:
  cloudflared:
    image: wisdomsky/cloudflared-web:latest
    restart: unless-stopped
    ports:
      - "14333:14333"
    networks:
      - default

networks:
  default:
    external: true
    name: project_scars_network