---
name: Tests - Central Server

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    name: python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CentralServer
    env:
      uv-cache-dir: /tmp/.uv-cache
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.24"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.uv-cache-dir }}
          key: uv-${{ runner.os }}-${{ hashFiles('CentralServer/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('CentralServer/uv.lock') }}
            uv-${{ runner.os }}

      - name: Install project
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest

      - name: Minimize uv cache
        run: uv cache prune --ci
